# Just a test config file

# Detector space parameters
detector:
  detector geometry:
    # detector geometry in millimeter.
    # Defined in cuboids with x_0, x_1, y_0, y_1, z_0, z_1
    # parameter 0 to 1: radial coordinates, x_0, x_1
    # parameter 2 to 3: tangential coordiantes, y_0, y_1
    # parameter 4 to 5: axial coordiantes, z_0, z_1
    # parameter 6: cuboid type identifier
    # parameter 7: cuboid attenuation coefficient
    [
      [10, 13, 0.5, 3.5, -0.5, 0.5, 1, 0.48],
      [10, 13, 3.5, 6.5, -0.5, 0.5, 2, 0.48],
      [10, 13, 6.5, 9.5, -0.5, 0.5, 3, 0.48],
      [10, 13, 9.5, 12.5, -0.5, 0.5, 4, 0.48],
      [10, 13, 12.5, 15.5, -0.5, 0.5, 5, 0.48],
      [10, 13, 15.5, 18.5, -0.5, 0.5, 6, 0.48],
      [10, 13, 18.5, 21.5, -0.5, 0.5, 7, 0.48],
      [10, 13, 21.5, 24.5, -0.5, 0.5, 8, 0.48],
      [0, 1, 0.5, 10.75, -0.5, 0.5, 0, 10],
      [0, 1, 11.25, 24.5, -0.5, 0.5, 0, 10],
      [0, 15, 0.0, 0.5, -0.5, 0.5, 0, 10],
      [0, 15, 24.5, 25.0, -0.5, 0.5, 0, 10]
    ]

  N-subdivision xyz: [2, 2, 1]
  active geometry indices: [8]

# Image space parameters
image:
  N-voxels xyz: [500, 500, 1]
  mm-per-voxel xyz: [.1, .1, 1.0]
  N-subdivision xyz: [4, 4, 1]

# Image space to detector space relative positioning
detector-to-image:
  # detector front edge to FOV center distance in radial direction
  # acceptable units are mm, cm, m
  radial distance: 50 mm
  # rotation of the detector relative to the FOV in degrees
  # rotation: 0

Debug:
  Point A: [-40, -12.5, 0.5]
  Point B: [11.5, 13.5, 0.5]

out npz filename: mpi-test.npz
